In [56]:
##================================================
## このセルを最初に実行せよ---Run this cell first.
##================================================
!wget -P . https://raw.githubusercontent.com/UTokyo-IPP/annex/master/assignments/pre7/iris.csv
!wget -P . https://raw.githubusercontent.com/UTokyo-IPP/annex/master/assignments/pre7/iris_modified.csv
!wget -P . https://raw.githubusercontent.com/UTokyo-IPP/annex/master/assignments/pre7/titanic.csv

--2022-05-22 06:28:06--  https://raw.githubusercontent.com/UTokyo-IPP/annex/master/assignments/pre7/iris.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3716 (3.6K) [text/plain]
Saving to: ‘./iris.csv.1’

iris.csv.1          100%[===================>]   3.63K  --.-KB/s    in 0s

2022-05-22 06:28:07 (65.2 MB/s) - ‘./iris.csv.1’ saved [3716/3716]

--2022-05-22 06:28:07--  https://raw.githubusercontent.com/UTokyo-IPP/annex/master/assignments/pre7/iris_modified.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-05-22 06:28:07 ERROR 404: Not Found.

--2022-05-22 06:28:07--  https://raw.githubusercontent.com/UTokyo-IPP/annex/master/assignments/pre7/titanic.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 44225 (43K) [text/plain]
Saving to: ‘./titanic.csv.1’

titanic.csv.1       100%[===================>]  43.19K  --.-KB/s    in 0.003s

2022-05-22 06:28:07 (13.0 MB/s) - ‘./titanic.csv.1’ saved [44225/44225]

# 第7回予習課題

[English version](https://colab.research.google.com/drive/1jMueYqJzCe37SPdczfKnbaGyxRrs4XJq)

## Pre7-1. pandasライブラリ

次のような計算を行う関数 `min_sepal_width(filepath, species, sepal_len)` を定義してください。

1. `filepath` で指定されたCSVファイルをデータフレームオブジェクト (`pandas.DataFrame`) としてロードし、
2. `'species'` 列の値が引数 `species`（値は `'setosa'`, `'virginica'`, `'versicolor'` のいずれか）の値と一致、かつ `'sepal_length'` 列の値が引数 `sepal_len` の値以上である行を抽出し、
3. その抽出した行から `'sepal_width'` 列の最小値を返す。

尚、データフレーム `df`の列 `'Name'`の最小値は `min` メソッドを使って `df['Name'].min()` とすれば計算できます。

In [57]:
##########################################################
##  <[ pre7-1-min_sepal_width ]> 解答セル (Answer cell)
##  このコメントの書き変えを禁ず (Never edit this comment)
##########################################################

QUESTION_EXISTS = False # 質問がある場合は True に変えて，このセル内のコメントとして質問を記述してください
                        # Change to True if you have questions, and describe them as comments in this cell

import pandas as pd

def min_sepal_width(filepath, species, sepal_len):
    iris_d = pd.read_csv(filepath)
    return iris_d[(iris_d['species'] == species) & (iris_d['sepal_length'] >= sepal_len)]['sepal_width'].min()

提出前に以下のテストセルを実行し、エラーがでないことを確認してください。

In [58]:
assert round(min_sepal_width('iris.csv', 'setosa', 5), 1) == 3.0
assert round(min_sepal_width('iris.csv', 'versicolor', 5), 1) == 2.0
assert round(min_sepal_width('iris.csv', 'virginica', 5), 1) == 2.2
assert round(min_sepal_width('iris.csv', 'setosa', 5.8), 1) == 4.0
assert round(min_sepal_width('iris.csv', 'versicolor', 5.8), 1) == 2.2
assert round(min_sepal_width('iris.csv', 'virginica', 5.8), 1) == 2.2

## Pre7-2. scikit-learnライブラリ

タイタニック号の乗船者のデータを含むCSVファイル `'titanic.csv'` には以下のように乗船者の特徴量とその乗船者が生存したかどうかの情報が含まれています。

In [59]:
# タイタニックデータセット
import pandas as pd
pd.read_csv('titanic.csv')[['Pclass','Fare','Age','Survived']].head()

   Pclass     Fare   Age  Survived
0       3   7.2500  22.0         0
1       1  71.2833  38.0         1
2       3   7.9250  26.0         1
3       1  53.1000  35.0         1
4       3   8.0500  35.0         0

以下の `predict_titanic` 関数を完成させてください。

1. CSVファイル`'titanic.csv'`を`pandas` モジュールのデータフレームオブジェクトとしてロード
2. 乗船者の3つの特徴量 （`Pclass`（客室の等級） と `Fare`（運賃）と`Age`（年齢）） からその乗船者が生存したか（ラベル `Survived` ：生存は`1`、非生存は`0`）を予測するモデルをロジスティック回帰を用いて学習し、その予測精度 （`accuracy_score`） を返す

`predict_titanic` 関数は `train_test_split` でデータを分割する際の `test_size` と `random_state` の値をそれぞれ `tsize` と `rstate` 引数で受け取ります。また、`train_test_split` では `stratify` にラベルデータを指定してください。

In [60]:
##########################################################
##  <[ pre7-2-predict_titanic ]> 解答セル (Answer cell)
##  このコメントの書き変えを禁ず (Never edit this comment)
##########################################################

QUESTION_EXISTS = False # 質問がある場合は True に変えて，このセル内のコメントとして質問を記述してください
                        # Change to True if you have questions, and describe them as comments in this cell

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

def predict_titanic(tsize, rstate):    
    df = pd.read_csv('titanic.csv')
    X = df[['Pclass','Fare','Age']].values
    y = df['Survived'].values
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=tsize, random_state=rstate, stratify=y)
    model=LogisticRegression(solver='lbfgs', multi_class='auto')
    
    model.fit(X_train, y_train)
    y_pre=model.predict(X_test)
    return accuracy_score(y_test, y_pre)

提出前に以下のテストセルを実行し、エラーがでないことを確認してください。

In [61]:
assert round(predict_titanic(0.3, 10), 2) == 0.73
assert round(predict_titanic(0.2, 10), 2) == 0.71
assert round(predict_titanic(0.3, 0), 2) == 0.71
assert round(predict_titanic(0.2, 0), 2) == 0.70